name: Django CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install PostgreSQL Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install libpq-dev

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r myapp/requirements.txt

    - name: Run Migrations
      run: python myapp/manage.py migrate

    - name: Run Account Tests
      run: python myapp/manage.py test accounts.tests
